//! Generated from imapflow's special-use tables (the generator was retired
//! with the Node tooling). Both lists are sorted by UTF-8 bytes; keep that
//! order when editing.

pub(crate) const NAMES: &[(&str, &str)] = &[
    ("aika", "\\Sent"),
    ("air a chur", "\\Sent"),
    ("am post cuirte", "\\Sent"),
    ("an chartlann", "\\Archive"),
    ("an sgudal", "\\Trash"),
    ("anfonwyd", "\\Sent"),
    ("archief", "\\Archive"),
    ("archieven", "\\Archive"),
    ("archif", "\\Archive"),
    ("archifau", "\\Archive"),
    ("archiv", "\\Archive"),
    ("archivados", "\\Archive"),
    ("archivar", "\\Archive"),
    ("archive", "\\Archive"),
    ("archives", "\\Archive"),
    ("archivi", "\\Archive"),
    ("archivio", "\\Archive"),
    ("archivo", "\\Archive"),
    ("archivos", "\\Archive"),
    ("archivovať", "\\Archive"),
    ("archivs", "\\Archive"),
    ("archivu", "\\Archive"),
    ("archiválás", "\\Archive"),
    ("archiwum", "\\Archive"),
    ("archiwy", "\\Archive"),
    ("archyvas", "\\Archive"),
    ("archyvuoti", "\\Archive"),
    ("archív", "\\Archive"),
    ("archívum", "\\Archive"),
    ("archívy", "\\Archive"),
    ("arewway", "\\Drafts"),
    ("argief", "\\Archive"),
    ("argiven", "\\Archive"),
    ("argyf", "\\Archive"),
    ("arhiiv", "\\Archive"),
    ("arhiv", "\\Archive"),
    ("arhiva", "\\Archive"),
    ("arhive", "\\Archive"),
    ("arhivi", "\\Archive"),
    ("arhivă", "\\Archive"),
    ("arhīvi", "\\Archive"),
    ("arhīvs", "\\Archive"),
    ("arkib", "\\Archive"),
    ("arkisto", "\\Archive"),
    ("arkiv", "\\Archive"),
    ("arkiva", "\\Archive"),
    ("arkiver", "\\Archive"),
    ("arkivo", "\\Archive"),
    ("arkivoje", "\\Archive"),
    ("arquivamento", "\\Archive"),
    ("arquivo", "\\Archive"),
    ("arquivo morto", "\\Archive"),
    ("arquivos", "\\Archive"),
    ("arsip", "\\Archive"),
    ("articole șterse", "\\Trash"),
    ("artxibatu", "\\Archive"),
    ("artxiboa", "\\Archive"),
    ("artxiboak", "\\Archive"),
    ("arxiu", "\\Archive"),
    ("arxiv", "\\Archive"),
    ("arxivlar", "\\Archive"),
    ("arşiv", "\\Archive"),
    ("arşivler", "\\Archive"),
    ("aspam", "\\Junk"),
    ("atkritne", "\\Trash"),
    ("aḥraz", "\\Archive"),
    ("ba brouillon", "\\Drafts"),
    ("basura", "\\Junk"),
    ("bidalia", "\\Sent"),
    ("bidaliak", "\\Sent"),
    ("bidalita", "\\Sent"),
    ("bidalitakoak", "\\Sent"),
    ("bin", "\\Trash"),
    ("borrador", "\\Drafts"),
    ("borradores", "\\Drafts"),
    ("borttaget", "\\Trash"),
    ("borttagna objekt", "\\Trash"),
    ("bosca bruscair", "\\Trash"),
    ("bozze", "\\Drafts"),
    ("brouilhedoù", "\\Drafts"),
    ("brouillonen", "\\Drafts"),
    ("brouillons", "\\Drafts"),
    ("brukalas", "\\Junk"),
    ("bruscar", "\\Trash"),
    ("bruttacopie", "\\Drafts"),
    ("bulk mail", "\\Junk"),
    ("bản thảo", "\\Drafts"),
    ("cajk", "\\Junk"),
    ("cartlanna", "\\Archive"),
    ("cestino", "\\Trash"),
    ("chanaster da palpiri", "\\Trash"),
    ("chiqitdon", "\\Trash"),
    ("ciorne", "\\Drafts"),
    ("concepten", "\\Drafts"),
    ("corbe a papiro", "\\Trash"),
    ("corbeille", "\\Trash"),
    ("correo basura", "\\Junk"),
    ("correo lixo", "\\Junk"),
    ("correo no deseado", "\\Junk"),
    ("correu brossa", "\\Junk"),
    ("corréu puxarra", "\\Junk"),
    ("courrier indésirable", "\\Junk"),
    ("coș de gunoi", "\\Trash"),
    ("curbella", "\\Trash"),
    ("currieru mandatu", "\\Sent"),
    ("danfonwyd", "\\Sent"),
    ("deleted", "\\Trash"),
    ("deleted items", "\\Trash"),
    ("deleted messages", "\\Trash"),
    ("diell", "\\Archive"),
    ("dielloù", "\\Archive"),
    ("dihantar", "\\Sent"),
    ("draf", "\\Drafts"),
    ("drafftiau", "\\Drafts"),
    ("draft", "\\Drafts"),
    ("drafts", "\\Drafts"),
    ("dramhaíl", "\\Junk"),
    ("dramhphost", "\\Junk"),
    ("dreachdan", "\\Drafts"),
    ("dréachtaí", "\\Drafts"),
    ("drög", "\\Drafts"),
    ("dzēstie vienumi", "\\Trash"),
    ("e rometsweng", "\\Sent"),
    ("e tindami", "\\Sent"),
    ("elementi eliminati", "\\Trash"),
    ("elementos borrados", "\\Trash"),
    ("elementos eliminados", "\\Trash"),
    ("elementos enviados", "\\Sent"),
    ("elements suprimits", "\\Trash"),
    ("eliminata", "\\Trash"),
    ("elküldött", "\\Sent"),
    ("elküldött elemek", "\\Sent"),
    ("elküldött üzenetek", "\\Sent"),
    ("elküldöttek", "\\Sent"),
    ("entwürfe", "\\Drafts"),
    ("enviadas", "\\Sent"),
    ("enviados", "\\Sent"),
    ("enviat", "\\Sent"),
    ("enviats", "\\Sent"),
    ("envoyés", "\\Sent"),
    ("erşîv", "\\Archive"),
    ("esborranys", "\\Drafts"),
    ("esbossos", "\\Drafts"),
    ("ethunyelweyo", "\\Sent"),
    ("expediate", "\\Sent"),
    ("ezipuru", "\\Sent"),
    ("ferstjoerd", "\\Sent"),
    ("garalamalar", "\\Drafts"),
    ("gelöscht", "\\Trash"),
    ("gelöschte elemente", "\\Trash"),
    ("gelöschte objekte", "\\Trash"),
    ("gemors", "\\Junk"),
    ("gemorspos", "\\Junk"),
    ("gereksiz", "\\Junk"),
    ("gesendet", "\\Sent"),
    ("gesendete", "\\Sent"),
    ("gesendete elemente", "\\Sent"),
    ("gestuur", "\\Sent"),
    ("geymsla", "\\Archive"),
    ("goym í skjalasavni", "\\Archive"),
    ("gunoi", "\\Trash"),
    ("gönderilmiş", "\\Sent"),
    ("gönderilmiş öğeler", "\\Sent"),
    ("göndərilənlər", "\\Sent"),
    ("hantar", "\\Sent"),
    ("hedhurina", "\\Trash"),
    ("iberilen", "\\Sent"),
    ("ihe edeturu", "\\Drafts"),
    ("iidrafti", "\\Drafts"),
    ("indesiderata", "\\Junk"),
    ("indesirate", "\\Junk"),
    ("indésirables", "\\Junk"),
    ("inviata", "\\Sent"),
    ("inviate", "\\Sent"),
    ("inviati", "\\Sent"),
    ("istenmeyen", "\\Junk"),
    ("istenmeyen e-posta", "\\Junk"),
    ("item dipadam", "\\Trash"),
    ("itens apagados", "\\Trash"),
    ("itens eliminados", "\\Trash"),
    ("itens excluídos", "\\Trash"),
    ("izinhlaka", "\\Drafts"),
    ("išsiųsti", "\\Sent"),
    ("išsiųsti laiškai", "\\Sent"),
    ("išsiųstieji", "\\Sent"),
    ("ištrinti", "\\Trash"),
    ("iɣbaren", "\\Archive"),
    ("i̇stenmeyen", "\\Junk"),
    ("iḍuman", "\\Trash"),
    ("jiskefet", "\\Trash"),
    ("jo`natilgan xatlar", "\\Sent"),
    ("jo‘natilgan", "\\Sent"),
    ("junk", "\\Junk"),
    ("junk e-mail", "\\Junk"),
    ("junk email", "\\Junk"),
    ("junk mail", "\\Junk"),
    ("junk-e-mail", "\\Junk"),
    ("juodraščiai", "\\Drafts"),
    ("jusamaj", "\\Drafts"),
    ("jêbirdank", "\\Trash"),
    ("kanta", "\\Trash"),
    ("kaset", "\\Sent"),
    ("kest", "\\Trash"),
    ("kladd", "\\Drafts"),
    ("kladdar", "\\Drafts"),
    ("kladder", "\\Drafts"),
    ("koncepty", "\\Drafts"),
    ("konsep", "\\Drafts"),
    ("konsepte", "\\Drafts"),
    ("konsepten", "\\Drafts"),
    ("kopie robocze", "\\Drafts"),
    ("kosz", "\\Trash"),
    ("koš", "\\Trash"),
    ("kuka", "\\Trash"),
    ("kustutatud", "\\Trash"),
    ("kustutatud üksused", "\\Trash"),
    ("kuthunyelwe", "\\Sent"),
    ("kéretlen", "\\Junk"),
    ("kôš", "\\Trash"),
    ("küldöttek", "\\Sent"),
    ("lasa", "\\Sent"),
    ("lastez", "\\Junk"),
    ("layihələr", "\\Drafts"),
    ("levélszemét", "\\Junk"),
    ("lixeira", "\\Trash"),
    ("lixo", "\\Trash"),
    ("lixo electrónico", "\\Junk"),
    ("lixo eletrónico", "\\Junk"),
    ("lixo eletrônico", "\\Junk"),
    ("lomtár", "\\Trash"),
    ("luonnokset", "\\Drafts"),
    ("lähetetyt", "\\Sent"),
    ("lưu trữ", "\\Archive"),
    ("malnetujo", "\\Drafts"),
    ("mel remeh", "\\Junk"),
    ("melnraksti", "\\Drafts"),
    ("meralo", "\\Drafts"),
    ("mesaje nedorite", "\\Junk"),
    ("mesaje nefinalizate", "\\Drafts"),
    ("mesaje trimise", "\\Sent"),
    ("mesazhe të padërguara", "\\Drafts"),
    ("messages envoyés", "\\Sent"),
    ("mga draft", "\\Drafts"),
    ("molwuj", "\\Trash"),
    ("mustandid", "\\Drafts"),
    ("møsn", "\\Junk"),
    ("mēstule", "\\Junk"),
    ("mēstules", "\\Junk"),
    ("mục đã xóa", "\\Trash"),
    ("nacerjenja", "\\Drafts"),
    ("nacrti", "\\Drafts"),
    ("naipadala", "\\Sent"),
    ("nalefa", "\\Sent"),
    ("napadala", "\\Sent"),
    ("naćiski", "\\Drafts"),
    ("nedovršene", "\\Drafts"),
    ("nedovršeno", "\\Drafts"),
    ("nepoželjne", "\\Junk"),
    ("nesolicitate", "\\Junk"),
    ("net-winske", "\\Junk"),
    ("nevyžiadaná pošta", "\\Junk"),
    ("nevyžádaná", "\\Junk"),
    ("nevyžádaná pošta", "\\Junk"),
    ("nevēlams", "\\Junk"),
    ("nezaželeno", "\\Junk"),
    ("neželena pošta", "\\Junk"),
    ("neželena sporočila", "\\Junk"),
    ("neželjena pošta", "\\Junk"),
    ("niechciane", "\\Junk"),
    ("no deseado", "\\Junk"),
    ("nosūtīts", "\\Sent"),
    ("nosūtītās", "\\Sent"),
    ("nosūtītās ziņas", "\\Sent"),
    ("nungiavischà", "\\Junk"),
    ("obrisane stavke", "\\Trash"),
    ("odeslaná pošta", "\\Sent"),
    ("odeslané", "\\Sent"),
    ("odoslaná", "\\Sent"),
    ("odoslaná pošta", "\\Sent"),
    ("odoslané", "\\Sent"),
    ("odpadkový kôš", "\\Trash"),
    ("odstraněná pošta", "\\Trash"),
    ("odstraněné položky", "\\Trash"),
    ("ongewenst", "\\Junk"),
    ("ongewenste e-mail", "\\Junk"),
    ("onvoltooid", "\\Drafts"),
    ("osnutki", "\\Drafts"),
    ("padala", "\\Sent"),
    ("papeleira", "\\Trash"),
    ("papelera", "\\Trash"),
    ("paperera", "\\Trash"),
    ("papierkorb", "\\Trash"),
    ("papirkorg", "\\Trash"),
    ("papirkurv", "\\Trash"),
    ("papjernik", "\\Trash"),
    ("papperskorg", "\\Trash"),
    ("papperskorgen", "\\Trash"),
    ("papīrgrozs", "\\Trash"),
    ("papīrkurvis", "\\Trash"),
    ("pesan terhapus", "\\Trash"),
    ("piszkozatok", "\\Drafts"),
    ("pod-lastez", "\\Trash"),
    ("poistetut", "\\Trash"),
    ("poslana pošta", "\\Sent"),
    ("poslane", "\\Sent"),
    ("poslano", "\\Sent"),
    ("poslané", "\\Sent"),
    ("poslato", "\\Sent"),
    ("posta indesiderata", "\\Junk"),
    ("posta indesirate", "\\Junk"),
    ("posta inviata", "\\Sent"),
    ("poubelle", "\\Trash"),
    ("pourriel", "\\Junk"),
    ("pourriels", "\\Junk"),
    ("praht", "\\Trash"),
    ("prullenbak", "\\Trash"),
    ("prügikast", "\\Trash"),
    ("puxarra", "\\Junk"),
    ("pósłane", "\\Sent"),
    ("pósłany", "\\Sent"),
    ("qaralamalar", "\\Drafts"),
    ("qoralama xatlar", "\\Drafts"),
    ("qoralamalar", "\\Drafts"),
    ("rascunhos", "\\Drafts"),
    ("rasimu", "\\Drafts"),
    ("reciclagem", "\\Trash"),
    ("reşnivîs", "\\Drafts"),
    ("roskaa", "\\Junk"),
    ("roskakori", "\\Trash"),
    ("roskaposti", "\\Junk"),
    ("roskapostit", "\\Junk"),
    ("rozepsané", "\\Drafts"),
    ("rubujo", "\\Trash"),
    ("rusl", "\\Trash"),
    ("ruslpóstur", "\\Junk"),
    ("rämps", "\\Junk"),
    ("rämpspost", "\\Junk"),
    ("saadetud", "\\Sent"),
    ("saadetud kirjad", "\\Sent"),
    ("saadetud üksused", "\\Sent"),
    ("savat", "\\Trash"),
    ("sbam", "\\Junk"),
    ("sbozs", "\\Drafts"),
    ("sbwriel", "\\Trash"),
    ("senditujo", "\\Sent"),
    ("sendt", "\\Sent"),
    ("sendt post", "\\Sent"),
    ("sendte", "\\Sent"),
    ("sendte beskeder", "\\Sent"),
    ("sent", "\\Sent"),
    ("sent items", "\\Sent"),
    ("sent messages", "\\Sent"),
    ("seolta", "\\Sent"),
    ("seq'", "\\Junk"),
    ("sgudal", "\\Trash"),
    ("silinmiş öğeler", "\\Trash"),
    ("siūsti", "\\Sent"),
    ("skica", "\\Drafts"),
    ("skice", "\\Drafts"),
    ("skickat", "\\Sent"),
    ("skitsur", "\\Drafts"),
    ("skjalageymsla", "\\Archive"),
    ("skrell", "\\Trash"),
    ("skräp", "\\Junk"),
    ("skräppost", "\\Junk"),
    ("sletta", "\\Trash"),
    ("slettede beskeder", "\\Trash"),
    ("slettede elementer", "\\Trash"),
    ("slettet", "\\Trash"),
    ("smeti", "\\Trash"),
    ("smeće", "\\Trash"),
    ("snippermandjie", "\\Trash"),
    ("sothach", "\\Junk"),
    ("spam", "\\Junk"),
    ("spamowanie", "\\Junk"),
    ("spamujo", "\\Junk"),
    ("stroboù", "\\Junk"),
    ("surat terhapus", "\\Trash"),
    ("szemét", "\\Junk"),
    ("szkice", "\\Drafts"),
    ("sända poster", "\\Sent"),
    ("sänt", "\\Sent"),
    ("søppelpost", "\\Junk"),
    ("sūtīt", "\\Sent"),
    ("səbət", "\\Trash"),
    ("taq yakb'äl", "\\Archive"),
    ("tasg-lannan", "\\Archive"),
    ("taslak", "\\Drafts"),
    ("taslaklar", "\\Drafts"),
    ("terkirim", "\\Sent"),
    ("thùng rác", "\\Trash"),
    ("thư nháp", "\\Drafts"),
    ("thư rác", "\\Junk"),
    ("thư đã gửi", "\\Sent"),
    ("ti fi ranṣẹ", "\\Sent"),
    ("titaq", "\\Sent"),
    ("tong sampah", "\\Trash"),
    ("tramess", "\\Sent"),
    ("trash", "\\Trash"),
    ("trimis", "\\Sent"),
    ("trimise", "\\Sent"),
    ("truilleis", "\\Junk"),
    ("tsararrun saƙonni", "\\Drafts"),
    ("ttwaznen", "\\Sent"),
    ("të dërguar", "\\Sent"),
    ("të dërguara", "\\Sent"),
    ("të pavlera", "\\Junk"),
    ("të pavlerë", "\\Junk"),
    ("törölt", "\\Trash"),
    ("törölt elemek", "\\Trash"),
    ("unviaos", "\\Sent"),
    ("unvios fechos", "\\Sent"),
    ("usunięte", "\\Trash"),
    ("usunięte wiadomości", "\\Trash"),
    ("utkast", "\\Drafts"),
    ("uzmetumi", "\\Drafts"),
    ("uønsket", "\\Junk"),
    ("uønsket e-mail", "\\Junk"),
    ("uønsket e-post", "\\Junk"),
    ("uønsket post", "\\Junk"),
    ("uønskt", "\\Junk"),
    ("vakiraoka", "\\Drafts"),
    ("verschéckt", "\\Sent"),
    ("versiones provisori", "\\Drafts"),
    ("verwijderde items", "\\Trash"),
    ("verzonden", "\\Sent"),
    ("verzonden berichten", "\\Sent"),
    ("vilivyotumwa", "\\Sent"),
    ("vymazané správy", "\\Trash"),
    ("vázlatok", "\\Drafts"),
    ("wersje robocze", "\\Drafts"),
    ("wiadomości-śmieci", "\\Junk"),
    ("wysłane", "\\Sent"),
    ("zabor-posta", "\\Junk"),
    ("zaborra", "\\Junk"),
    ("zakarrontzia", "\\Trash"),
    ("zirriborroak", "\\Drafts"),
    ("àwọn àkọpamọ́", "\\Drafts"),
    ("çöp", "\\Trash"),
    ("çöp kutusu", "\\Trash"),
    ("éléments envoyés", "\\Sent"),
    ("éléments supprimés", "\\Trash"),
    ("önemsiz", "\\Junk"),
    ("čapor", "\\Junk"),
    ("đã gửi", "\\Sent"),
    ("şandî", "\\Sent"),
    ("šiukšliadėžė", "\\Trash"),
    ("šiukšlinė", "\\Trash"),
    ("šiukšlių dėžė", "\\Trash"),
    ("šiukšlės", "\\Junk"),
    ("šlamštas", "\\Junk"),
    ("șterse", "\\Trash"),
    ("ανεπιθύμητα", "\\Junk"),
    ("ανεπιθύμητη αλληλογραφία", "\\Junk"),
    ("απεσταλμένα", "\\Sent"),
    ("απορρίμματα", "\\Trash"),
    ("αρχειοθέτηση", "\\Archive"),
    ("αρχειοθήκη", "\\Archive"),
    ("διαγραμμένα", "\\Trash"),
    ("κάδος απορριμάτων", "\\Trash"),
    ("κάδος απορριμμάτων", "\\Trash"),
    ("προσχέδια", "\\Drafts"),
    ("πρόχειρα", "\\Drafts"),
    ("σταλθέντα", "\\Sent"),
    ("адпраўлена", "\\Sent"),
    ("архив", "\\Archive"),
    ("архива", "\\Archive"),
    ("архиве", "\\Archive"),
    ("архиви", "\\Archive"),
    ("архивирай", "\\Archive"),
    ("архивтер", "\\Archive"),
    ("архивы", "\\Archive"),
    ("архів", "\\Archive"),
    ("архіви", "\\Archive"),
    ("архівы", "\\Archive"),
    ("архіў", "\\Archive"),
    ("видалені", "\\Trash"),
    ("выдаленыя", "\\Trash"),
    ("драфтови", "\\Drafts"),
    ("жиберилген", "\\Sent"),
    ("жоба жазбалар", "\\Drafts"),
    ("жобалар", "\\Drafts"),
    ("жойылғандар", "\\Trash"),
    ("жіберілген", "\\Sent"),
    ("жіберілген хаттар", "\\Sent"),
    ("жіберілгендер", "\\Sent"),
    ("избришани", "\\Trash"),
    ("изпратени", "\\Sent"),
    ("изпратени писма", "\\Sent"),
    ("изтрити", "\\Trash"),
    ("илгээсэн", "\\Sent"),
    ("ирсол шуд", "\\Sent"),
    ("испратени", "\\Sent"),
    ("испратено", "\\Sent"),
    ("канта", "\\Trash"),
    ("корзина", "\\Trash"),
    ("корпа", "\\Trash"),
    ("кошик", "\\Trash"),
    ("кошче", "\\Trash"),
    ("мұрағат", "\\Archive"),
    ("надіслані", "\\Sent"),
    ("нацрти", "\\Drafts"),
    ("небажана пошта", "\\Junk"),
    ("недовршене", "\\Drafts"),
    ("недовршено", "\\Drafts"),
    ("нежелана поща", "\\Junk"),
    ("нежелательная почта", "\\Junk"),
    ("непажаданая пошта", "\\Junk"),
    ("непожељна пошта", "\\Junk"),
    ("непожељне", "\\Junk"),
    ("непожељно", "\\Junk"),
    ("непосакувана пошта", "\\Junk"),
    ("непратени", "\\Drafts"),
    ("нооргууд", "\\Drafts"),
    ("ноорог", "\\Drafts"),
    ("обрисане ставке", "\\Trash"),
    ("отправленные", "\\Sent"),
    ("пасланыя", "\\Sent"),
    ("послате", "\\Sent"),
    ("послато", "\\Sent"),
    ("пратени", "\\Sent"),
    ("себет", "\\Trash"),
    ("сиёҳнавис", "\\Drafts"),
    ("скици", "\\Drafts"),
    ("сметніца", "\\Trash"),
    ("смеће", "\\Trash"),
    ("смітник", "\\Trash"),
    ("спам", "\\Junk"),
    ("удаленные", "\\Trash"),
    ("удалённые", "\\Trash"),
    ("хогийн сав", "\\Trash"),
    ("хомаки хатлар", "\\Drafts"),
    ("чарнавікі", "\\Drafts"),
    ("чернетки", "\\Drafts"),
    ("чернови", "\\Drafts"),
    ("черновики", "\\Drafts"),
    ("черновиктер", "\\Drafts"),
    ("шимай қағаз", "\\Drafts"),
    ("юборилган", "\\Sent"),
    ("қалаусыз пошта", "\\Junk"),
    ("қоқыс шелегі", "\\Trash"),
    ("աղբարկղ", "\\Trash"),
    ("անպիտան", "\\Junk"),
    ("արխիվ", "\\Archive"),
    ("արխիւներ", "\\Archive"),
    ("թափոն", "\\Junk"),
    ("ուղարկուած", "\\Sent"),
    ("ուղարկված", "\\Sent"),
    ("սեւագրեր", "\\Drafts"),
    ("սպամ", "\\Junk"),
    ("ארכיון", "\\Archive"),
    ("אשפה", "\\Trash"),
    ("דואר זבל", "\\Junk"),
    ("זבל", "\\Junk"),
    ("טיוטות", "\\Drafts"),
    ("נשלח", "\\Sent"),
    ("נשלחו", "\\Sent"),
    ("פריטים שנמחקו", "\\Trash"),
    ("פריטים שנשלחו", "\\Sent"),
    ("أرشفة", "\\Archive"),
    ("أرشيف", "\\Archive"),
    ("ئارخىپ", "\\Archive"),
    ("ئەرشیف", "\\Archive"),
    ("ئەۋەتىلگەن", "\\Sent"),
    ("ارسال شده", "\\Sent"),
    ("ارسالی", "\\Sent"),
    ("ارشیو", "\\Archive"),
    ("اشغال دانی", "\\Trash"),
    ("الأرشيف", "\\Archive"),
    ("البريد المرسل", "\\Sent"),
    ("الرسائل العشوائية", "\\Junk"),
    ("الرسائل غير المرغوب فيها", "\\Junk"),
    ("العناصر المحذوفة", "\\Trash"),
    ("المرسل", "\\Sent"),
    ("المرسلة", "\\Sent"),
    ("المسودات", "\\Drafts"),
    ("المهملات", "\\Trash"),
    ("المُرسَل", "\\Sent"),
    ("بارليک", "\\Drafts"),
    ("بایگانی", "\\Archive"),
    ("بنجل", "\\Junk"),
    ("بھیجا ہوا میل", "\\Sent"),
    ("بھیجے گئے", "\\Sent"),
    ("بیکاره", "\\Junk"),
    ("بێکه\u{200c}ڵک", "\\Junk"),
    ("جنک", "\\Junk"),
    ("جنک میل", "\\Junk"),
    ("ردی کی ٹوکری", "\\Trash"),
    ("زباله\u{200c}دان", "\\Trash"),
    ("زبڵدان", "\\Trash"),
    ("سوزمژہ", "\\Sent"),
    ("سُخام", "\\Junk"),
    ("غير المرغوب", "\\Junk"),
    ("قوليازمىلار", "\\Drafts"),
    ("لېږل شوي ليکونه", "\\Sent"),
    ("لېګل شوی", "\\Sent"),
    ("مسودات", "\\Drafts"),
    ("مسوّدات", "\\Drafts"),
    ("موارد ارسال شده", "\\Sent"),
    ("موارد حذف شده", "\\Trash"),
    ("موسودې", "\\Drafts"),
    ("مُرسَل", "\\Sent"),
    ("مُهملات", "\\Trash"),
    ("نامه های ناتکمیل", "\\Drafts"),
    ("نێردراو", "\\Sent"),
    ("هرزنامه", "\\Junk"),
    ("پیش نویسها", "\\Drafts"),
    ("پیش\u{200c}نویس\u{200c}ها", "\\Drafts"),
    ("ڈرافٹ", "\\Drafts"),
    ("ڈرافٹ/", "\\Drafts"),
    ("ڕه\u{200c}شنووسەکان", "\\Drafts"),
    ("کثافت دانۍ", "\\Trash"),
    ("कचरा", "\\Trash"),
    ("कचरा पेटी", "\\Trash"),
    ("जतन केलेला", "\\Archive"),
    ("ड्राफ़ट", "\\Drafts"),
    ("ड्राफ़्ट", "\\Drafts"),
    ("ड्राफ्ट", "\\Drafts"),
    ("ड्राफ्टहरू", "\\Drafts"),
    ("नको असलेले कचरा संदेश", "\\Junk"),
    ("पठईएका मेलहरु", "\\Sent"),
    ("पाठवलेले", "\\Sent"),
    ("पाठविले", "\\Sent"),
    ("पाठविलेले", "\\Sent"),
    ("प्रारूप", "\\Drafts"),
    ("प्रेषित", "\\Sent"),
    ("भेजा गया", "\\Sent"),
    ("भेजे गए", "\\Sent"),
    ("मसुदा", "\\Drafts"),
    ("रद्दी", "\\Trash"),
    ("रद्दी टोकरी", "\\Trash"),
    ("संग्रह", "\\Archive"),
    ("स्पाम", "\\Junk"),
    ("स्पैम", "\\Junk"),
    ("আজেবাজে মেইল", "\\Junk"),
    ("খসড়া", "\\Drafts"),
    ("ঝুড়ি", "\\Trash"),
    ("ডাস্টবিন", "\\Trash"),
    ("ড্ৰাফ্ট", "\\Drafts"),
    ("পাঠানো হয়েছে", "\\Sent"),
    ("প্রেরিত", "\\Sent"),
    ("প্রেরিত(পাঠানো মেইল)", "\\Sent"),
    ("প্ৰেৰিত", "\\Sent"),
    ("ਡ੍ਰਾਫਟ", "\\Drafts"),
    ("ਭੇਜੇ", "\\Sent"),
    ("કચરો", "\\Trash"),
    ("ડ્રાફ્ટ", "\\Drafts"),
    ("ડ્રાફ્ટસ", "\\Drafts"),
    ("મોકલેલા", "\\Sent"),
    ("મોકલેલ્યા", "\\Sent"),
    ("ଡ୍ରାଫ୍ଟ", "\\Drafts"),
    ("ପଠାଗଲା", "\\Sent"),
    ("அனுப்பிய அஞ்சல்", "\\Sent"),
    ("அனுப்பியவை", "\\Sent"),
    ("எரிதம்", "\\Junk"),
    ("குப்பை", "\\Trash"),
    ("வரைவுகள்", "\\Drafts"),
    ("చిత్తు ప్రతులు", "\\Drafts"),
    ("పంపించబడింది", "\\Sent"),
    ("ಕರಡುಗಳು", "\\Drafts"),
    ("ಕಳುಹಿಸಲಾದ", "\\Sent"),
    ("അയച്ചവ", "\\Sent"),
    ("അയച്ചു", "\\Sent"),
    ("ആവശ്യമില്ലാത്തവ", "\\Junk"),
    ("കരടുകള്\u{200d}", "\\Drafts"),
    ("ചവറ്റുകുട്ട", "\\Trash"),
    ("ഡ്രാഫ്റ്റുകൾ", "\\Drafts"),
    ("പൂര്\u{200d}ത്തിയാകാത്തവ", "\\Drafts"),
    ("ശേഖരം", "\\Archive"),
    ("ඉවතලන බඳුන", "\\Trash"),
    ("කටු සටහන්", "\\Drafts"),
    ("කෙටුම් පත්", "\\Drafts"),
    ("යැවු පණිවුඩ", "\\Sent"),
    ("යැවූ", "\\Sent"),
    ("සංරක්\u{200d}ෂණය", "\\Archive"),
    ("සුන්බුන්", "\\Junk"),
    ("กล่องจดหมายขยะ", "\\Junk"),
    ("กล่องจดหมายร่าง", "\\Drafts"),
    ("การเก็บถาวร", "\\Archive"),
    ("ขยะ", "\\Junk"),
    ("ฉบับร่าง", "\\Drafts"),
    ("ถังขยะ", "\\Trash"),
    ("ที่ส่งแล้ว", "\\Sent"),
    ("ที่เก็บถาวร", "\\Archive"),
    ("รายการที่ลบ", "\\Trash"),
    ("ร่าง", "\\Drafts"),
    ("สแปม", "\\Junk"),
    ("ส่ง", "\\Sent"),
    ("ส่งแล้ว", "\\Sent"),
    ("อีเมลขยะ", "\\Junk"),
    ("လိက်အပြောံ", "\\Drafts"),
    ("არქივები", "\\Archive"),
    ("არქივი", "\\Archive"),
    ("გაგზავნილი", "\\Sent"),
    ("დროებითი", "\\Drafts"),
    ("მონახაზები", "\\Drafts"),
    ("ნაგავი", "\\Trash"),
    ("სპამი", "\\Junk"),
    ("ურნა", "\\Trash"),
    ("წაშლილი", "\\Trash"),
    ("წინასწარი", "\\Drafts"),
    ("ჯართი", "\\Junk"),
    ("ረቂቆች", "\\Drafts"),
    ("እንዳቅንጠመንጢ", "\\Junk"),
    ("እንዳጉሓፍ", "\\Trash"),
    ("ወጡን ጽሑፍ", "\\Drafts"),
    ("ዝተለኣኸ", "\\Sent"),
    ("የተላኩ", "\\Sent"),
    ("ធុងសំរាម", "\\Trash"),
    ("បាន\u{200b}ផ្ញើ", "\\Sent"),
    ("ប័ណ្ណសារ", "\\Archive"),
    ("ប័ណ្ណសារ\u{200b}", "\\Archive"),
    ("សារព្រាង", "\\Drafts"),
    ("សេចក្ដី\u{200b}ព្រាង\u{200b}", "\\Drafts"),
    ("សំបុត្រដែលបានបញ្ជូន", "\\Sent"),
    ("សំបុត្រពង្រៀង", "\\Drafts"),
    ("សំបុត្រមិនល្អ", "\\Junk"),
    ("ឥត\u{200b}បាន\u{200b}ការ", "\\Junk"),
    ("ごみ箱", "\\Trash"),
    ("アーカイブ", "\\Archive"),
    ("ゴミ箱", "\\Trash"),
    ("下書き", "\\Drafts"),
    ("備存", "\\Archive"),
    ("削除済みアイテム", "\\Trash"),
    ("回收站", "\\Trash"),
    ("垃圾", "\\Junk"),
    ("垃圾信件", "\\Junk"),
    ("垃圾桶", "\\Trash"),
    ("垃圾邮件", "\\Junk"),
    ("垃圾郵件", "\\Junk"),
    ("垃圾電郵", "\\Junk"),
    ("存档", "\\Archive"),
    ("存檔", "\\Archive"),
    ("寄件備份", "\\Sent"),
    ("封存", "\\Archive"),
    ("已删除邮件", "\\Trash"),
    ("已刪除項目", "\\Trash"),
    ("已发信息", "\\Sent"),
    ("已发送", "\\Sent"),
    ("已发送消息", "\\Sent"),
    ("已发送邮件", "\\Sent"),
    ("废件箱", "\\Trash"),
    ("归档", "\\Archive"),
    ("草稿", "\\Drafts"),
    ("草稿匣", "\\Drafts"),
    ("草稿箱", "\\Drafts"),
    ("迷惑メール", "\\Junk"),
    ("送信済み", "\\Sent"),
    ("送信済みアイテム", "\\Sent"),
    ("送信済みトレイ", "\\Sent"),
    ("送信済みメール", "\\Sent"),
    ("발신 메시지", "\\Sent"),
    ("보관 편지함", "\\Archive"),
    ("보관함", "\\Archive"),
    ("보낸 편지함", "\\Sent"),
    ("보냄", "\\Sent"),
    ("스팸", "\\Junk"),
    ("스팸 편지함", "\\Junk"),
    ("임시 보관함", "\\Drafts"),
    ("저장 편지함", "\\Archive"),
    ("정크", "\\Junk"),
    ("정크 메일", "\\Junk"),
    ("지운 편지함", "\\Trash"),
    ("초안", "\\Drafts"),
    ("휴지통", "\\Trash"),
];

pub(crate) const GENERIC_TOKENS: &[&str] = &[
    "berichten",
    "beskeder",
    "correo",
    "courrier",
    "e",
    "elemente",
    "elementen",
    "elementer",
    "elementi",
    "elementos",
    "elementy",
    "email",
    "emails",
    "folder",
    "item",
    "items",
    "itens",
    "kirjad",
    "mail",
    "mails",
    "meldinger",
    "mensagens",
    "mensajes",
    "mesajlar",
    "message",
    "messages",
    "messaggi",
    "my",
    "nachrichten",
    "objekt",
    "objekte",
    "objekten",
    "objekter",
    "poczta",
    "položky",
    "post",
    "posta",
    "poster",
    "pošta",
    "správy",
    "viestit",
    "wiadomości",
    "éléments",
    "öğeler",
    "μηνύματα",
    "στοιχεία",
    "письма",
    "письмо",
    "пошта",
    "сообщения",
    "элементы",
];
