//! omni_core::js and omni_core::digest against V8 reference output.
//!
//! `tests/golden/js.json` is generated by `scripts/golden-js.mts` (node 24,
//! default locale en-US, the TS `src/utils/fingerprint.ts`).
#![allow(clippy::expect_used)]

use std::cmp::Ordering;
use std::sync::LazyLock;

use omni_core::digest::{digest, fingerprint_evidence};
use omni_core::js;
use serde_json::Value;

static GOLDEN: LazyLock<Value> = LazyLock::new(|| {
    let text = include_str!("golden/js.json");
    serde_json::from_str(text).expect("golden js.json parses")
});

fn section(name: &str) -> &'static Vec<Value> {
    GOLDEN[name].as_array().expect("golden section is an array")
}

fn str_of(v: &Value) -> &str {
    v.as_str().expect("string")
}

fn f64_from_bits_hex(hex: &str) -> f64 {
    f64::from_bits(u64::from_str_radix(hex, 16).expect("hex bits"))
}

fn usize_of(v: &Value) -> usize {
    usize::try_from(v.as_u64().expect("index")).expect("fits usize")
}

#[test]
fn golden_locale_is_root_compatible() {
    assert_eq!(GOLDEN["locale"], "en-US");
}

#[test]
fn utf16_len_and_slice_match_v8() {
    let mut checked = 0;
    for case in section("utf16") {
        let s = str_of(&case["s"]);
        assert_eq!(js::utf16_len(s), usize_of(&case["len"]), "length of {s:?}");
        for slice in case["slices"].as_array().expect("slices") {
            let (start, end) = (usize_of(&slice[0]), usize_of(&slice[1]));
            assert_eq!(
                js::utf16_slice(s, start, end),
                str_of(&slice[2]),
                "{s:?}.slice({start}, {end})"
            );
            checked += 1;
        }
    }
    assert!(checked > 300);
}

#[test]
fn number_to_string_matches_v8() {
    let cases = section("numbers");
    assert!(cases.len() > 4000);
    for case in cases {
        let n = f64_from_bits_hex(str_of(&case[0]));
        assert_eq!(
            js::number_to_string(n),
            str_of(&case[1]),
            "bits {}",
            case[0]
        );
    }
}

#[test]
fn json_stringify_matches_v8() {
    for case in section("stringify") {
        let text = str_of(&case["text"]);
        let value: Value = serde_json::from_str(text).expect("case parses");
        assert_eq!(
            js::json_stringify(&value),
            str_of(&case["compact"]),
            "{text}"
        );
        assert_eq!(
            js::json_stringify_pretty2(&value),
            str_of(&case["pretty2"]),
            "{text}"
        );
    }
}

#[test]
fn locale_compare_matches_v8() {
    let words: Vec<&str> = section("localeWords").iter().map(str_of).collect();
    let matrix = section("localeCompare");
    let mut mismatches = Vec::new();
    for (i, a) in words.iter().enumerate() {
        let row = matrix[i].as_array().expect("row");
        for (j, b) in words.iter().enumerate() {
            let expected = match row[j].as_i64().expect("sign") {
                -1 => Ordering::Less,
                0 => Ordering::Equal,
                _ => Ordering::Greater,
            };
            let actual = js::locale_compare(a, b);
            if actual != expected {
                mismatches.push(format!("{a:?} vs {b:?}: V8 {expected:?}, Rust {actual:?}"));
            }
        }
    }
    assert!(mismatches.is_empty(), "{}", mismatches.join("\n"));
}

#[test]
fn encode_uri_component_matches_v8() {
    for case in section("encodeURIComponent") {
        assert_eq!(js::encode_uri_component(str_of(&case[0])), str_of(&case[1]));
    }
}

#[test]
fn to_iso_string_matches_v8() {
    for case in section("toISOString") {
        let ms = case[0].as_i64().expect("ms");
        assert_eq!(js::to_iso_string(ms), str_of(&case[1]), "{ms}");
    }
}

#[test]
fn string_to_number_matches_v8() {
    for case in section("stringToNumber") {
        let s = str_of(&case[0]);
        let expected = f64_from_bits_hex(str_of(&case[1]));
        let actual = js::string_to_number(s);
        if expected.is_nan() {
            assert!(actual.is_nan(), "Number({s:?}) should be NaN, got {actual}");
        } else {
            assert_eq!(actual.to_bits(), expected.to_bits(), "Number({s:?})");
        }
    }
}

#[test]
fn digest_matches_node() {
    for case in section("digest") {
        assert_eq!(digest(str_of(&case[0])), str_of(&case[1]));
    }
}

#[test]
fn fingerprint_evidence_matches_ts() {
    for case in section("fingerprint") {
        let items = case["items"].as_array().expect("items");
        let actual = fingerprint_evidence(items, |item| {
            item["evidenceId"].as_str().expect("evidenceId")
        })
        .expect("objects");
        assert_eq!(actual, str_of(&case["expected"]));
    }
}

#[test]
fn fingerprint_spec_pinned_value() {
    // src/utils/fingerprint.spec.ts: "produces a pinned, byte-stable fingerprint".
    let b = serde_json::json!({"evidenceId": "b", "kind": "listen", "showTitle": "Show B", "observedAt": 200});
    let a = serde_json::json!({"evidenceId": "a", "kind": "listen", "showTitle": "Show A", "observedAt": 100, "starred": true});
    fn id(v: &Value) -> &str {
        v["evidenceId"].as_str().expect("id")
    }
    let pinned = fingerprint_evidence(&[b.clone(), a.clone()], id).expect("objects");
    assert_eq!(pinned, "f09fcee7d85f7dc9f02e0af0");
    assert_eq!(
        fingerprint_evidence(&[a.clone(), b.clone()], id).expect("objects"),
        pinned
    );
    let mut changed = b;
    changed["completion"] = serde_json::json!(0.5);
    assert_ne!(
        fingerprint_evidence(&[a, changed], id).expect("objects"),
        pinned
    );
}
