import { baseConfigSchema, logConfig, stringBoolean } from "@micthiesen/mitools/config";
import { z } from "zod";
import { validateMcpTokenConfiguration } from "../mcp/auth.js";

const optionalPositiveInt = z.preprocess(
  (value) => (value === "" ? undefined : value),
  z.coerce.number().int().positive().optional(),
);

const optionalNonNegativeNumber = z.preprocess(
  (value) => (value === "" ? undefined : value),
  z.coerce.number().nonnegative().optional(),
);

const configSchema = baseConfigSchema
  .extend({
    KICK_CLIENT_ID: z.string().optional(),
    KICK_CLIENT_SECRET: z.string().optional(),
    OFFLINE_NOTIFICATIONS: z
      .string()
      .optional()
      .default("true")
      .transform(stringBoolean),
    PUSHOVER_LIVE_TOKEN: z.string().optional(),
    /** Enables the Boris-local livestream semantic/audio intelligence layer. */
    LIVESTREAM_INTELLIGENCE_ENABLED: z
      .string()
      .optional()
      .default("false")
      .transform(stringBoolean),
    LIVESTREAM_INTELLIGENCE_MODEL: z.literal("openai:gpt-5.6-luna").optional(),
    /** Hard monthly ceiling for this feature's metered model calls. */
    LIVESTREAM_MONTHLY_BUDGET_USD: optionalNonNegativeNumber
      .pipe(z.number().max(10))
      .default(3),
    /** Directory containing the bundled sherpa-onnx models. */
    LIVESTREAM_MODEL_DIR: z
      .string()
      .optional()
      .default("/app/assets/livestream-intelligence/models"),
    /** JSON enrollment vectors generated by the speaker-enrollment tool. */
    LIVESTREAM_DESTINY_VOICEPRINT_PATH: z.string().optional(),
    /** Minimum cosine similarity for a candidate Destiny speech window. */
    LIVESTREAM_DESTINY_SPEAKER_THRESHOLD: z.coerce.number().min(0).max(1).default(0.62),
    /** Maximum DGG-present non-Destiny streams sampled for voice presence. */
    LIVESTREAM_MAX_VOICE_TARGETS: optionalPositiveInt.default(3),
    /** Seconds captured per lightweight voice-presence sample. */
    LIVESTREAM_VOICE_SAMPLE_SECONDS: optionalPositiveInt.default(18),
    /** Minimum seconds between voice-presence samples for one stream. */
    LIVESTREAM_VOICE_SAMPLE_INTERVAL_SECONDS: optionalPositiveInt.default(45),
    /** Seconds captured for each rolling semantic summary. */
    LIVESTREAM_SUMMARY_SAMPLE_SECONDS: optionalPositiveInt.default(75),
    /** Minimum seconds between rolling summaries for one stream. */
    LIVESTREAM_SUMMARY_INTERVAL_SECONDS: optionalPositiveInt.default(480),
    PUSHOVER_CALENDAR_TOKEN: z.string().optional(),
    PUSHOVER_BRIEFING_TOKEN: z.string().optional(),
    PUSHOVER_WORKSPACE_TOKEN: z.string().optional(),
    BRIEFING_MODEL: z.string().optional(),
    WORKSPACE_MODEL: z.string().optional(),
    WORKSPACE_SCHEDULE: z.string().optional().default("0 0 9 * * 0"),
    WORKSPACES_PUBLIC_URL: z
      .string()
      .optional()
      .default("http://omni.boris")
      .transform((s) => s.replace(/\/+$/, "")),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().optional(),
    ANTHROPIC_API_KEY: z.string().optional(),
    OPENAI_API_KEY: z.string().optional(),
    TAVILY_API_KEY: z.string().optional(),
    LOGS_PATH: z.string().optional(),
    CHANNELS_CONFIG_PATH: z.string().optional(),
    BRIEFINGS_PATH: z.string().optional(),
    /**
     * Which email transport monitors the mailbox: Fastmail JMAP or iCloud
     * IMAP. Defaults to fastmail while FASTMAIL_API_TOKEN is set (safe during
     * the migration overlap), else icloud when its credentials exist.
     */
    EMAIL_TRANSPORT: z.enum(["fastmail", "icloud"]).optional(),
    /** CalDAV backend for calendar-event writes; defaults to EMAIL_TRANSPORT.
     * Set explicitly (icloud) once calendar data migrates ahead of the MX cutover. */
    CALDAV_PROVIDER: z.enum(["fastmail", "icloud"]).optional(),
    FASTMAIL_API_TOKEN: z.string().optional(),
    FASTMAIL_APP_PASSWORD: z.string().optional(),
    FASTMAIL_USERNAME: z.string().optional(),
    /** iCloud primary username (micthiesen@icloud.com — NOT the custom-domain
     * address); shared by IMAP and CalDAV. */
    ICLOUD_USERNAME: z.string().optional(),
    /** App-specific password (account.apple.com → App-Specific Passwords). */
    ICLOUD_APP_PASSWORD: z.string().optional(),
    /** Display name of the iCloud calendar to write events to (e.g. "Personal"). */
    ICLOUD_CALENDAR_NAME: z.string().optional(),
    /** Optional: previously discovered collection URL; skips discovery. */
    ICLOUD_CALENDAR_URL: z.string().optional(),
    /** The user's own receiving address (self-sent-mail filter); defaults to
     * FASTMAIL_USERNAME for compatibility. */
    EMAIL_SELF_ADDRESS: z.string().optional(),
    PARCEL_API_KEY: z.string().optional(),
    EXTRACTION_MODEL: z.string().optional(),
    /** Calendar extraction gets its own (stronger) model; falls back in registry. */
    CALENDAR_EXTRACTION_MODEL: z.string().optional(),
    /** Cheap shared email triage classifier (parcel + calendar relevance). */
    TRIAGE_MODEL: z.string().optional(),
    FASTMAIL_CALENDAR_ID: z.string().optional(),
    TMDB_API_KEY: z.string().optional(),
    RECS_SHORTLIST_MODEL: z.string().optional(),
    RECS_SELECTION_MODEL: z.string().optional(),
    TASTE_REFLECTION_MODEL: z.string().optional(),
    TASTE_REFLECTION_SCHEDULE: z.string().optional().default("0 0 4 * * 0"),
    RECS_SCHEDULE: z.string().optional().default("0 0 17 * * 1,3,5"),
    RECS_PUBLIC_URL: z.string().optional().default("http://omni.boris"),
    PUSHOVER_RECS_TOKEN: z.string().optional(),
    PODCAST_RECS_SCHEDULE: z.string().optional().default("0 0 11 * * 1,3,5"),
    PODCAST_TASTE_PATH: z.string().optional(),
    PODCAST_TASTE_REFLECTION_MODEL: z.string().optional(),
    PODCAST_TASTE_REFLECTION_SCHEDULE: z.string().optional().default("0 0 5 * * 0"),
    PUSHOVER_PODCAST_TOKEN: z.string().optional(),
    CASTRO_ACCESS_ID: z.string().uuid().optional(),
    CASTRO_SECRET_KEY: z.string().optional(),
    PODCASTINDEX_KEY: z.string().optional(),
    PODCASTINDEX_SECRET: z.string().optional(),
    /** Max followed voices person-searched per run (rotates across runs). */
    PODCAST_VOICE_ROTATION_MAX: optionalPositiveInt.default(12),
    /** Cap on Tier-1 guest-appearance picks per run (bursts like book tours). */
    PODCAST_MAX_GUEST_PICKS: optionalPositiveInt.default(6),
    PLEX_URL: z.string().optional(),
    PLEX_TOKEN: z.string().optional(),
    PLEX_ACCOUNT_ID: optionalPositiveInt,
    RADARR_URL: z.string().optional(),
    RADARR_API_KEY: z.string().optional(),
    RADARR_ROOT_FOLDER_PATH: z.string().optional(),
    RADARR_QUALITY_PROFILE_ID: optionalPositiveInt,
    SONARR_URL: z.string().optional(),
    SONARR_API_KEY: z.string().optional(),
    SONARR_ROOT_FOLDER_PATH: z.string().optional(),
    SONARR_QUALITY_PROFILE_ID: optionalPositiveInt,
    TZ: z.string().optional().default("America/Vancouver"),
    SMTP_HOST: z.string().optional(),
    SMTP_PORT: z.coerce.number().optional().default(587),
    SMTP_USER: z.string().optional(),
    SMTP_PASS: z.string().optional(),
    EMAIL_FROM: z.string().optional(),
    LOGS_EMAIL_TO: z.string().optional(),
    WHISKER_CREDENTIALS: z
      .string()
      .optional()
      .transform((s) => {
        if (!s) return undefined;
        const [email, ...rest] = s.split(":");
        const password = rest.join(":");
        if (!email || !password) {
          throw new Error("WHISKER_CREDENTIALS must be email:password");
        }
        return { email, password };
      }),
    FRONTEND_PORT: z.coerce.number().optional().default(3000),
    /** Bearer token for the private streamable-HTTP MCP endpoint. */
    OMNI_MCP_TOKEN: z.string().optional(),
    /** Enables MCP printing through one fixed IPP or IPPS printer endpoint. */
    PRINTER_IPP_URL: z
      .string()
      .url()
      .optional()
      .refine(
        (value) =>
          value === undefined || ["ipp:", "ipps:"].includes(new URL(value).protocol),
        "PRINTER_IPP_URL must use ipp:// or ipps://",
      ),
    /** Enables PressPods (article → podcast) and authenticates its public routes. */
    PRESSPODS_AUTH_TOKEN: z.string().optional(),
    /**
     * Public origin for RSS enclosure URLs (e.g. the nginx-exposed host).
     * When unset, the origin is derived from each request's forwarded headers.
     */
    PRESSPODS_PUBLIC_URL: z
      .string()
      .optional()
      .transform((s) => s?.replace(/\/+$/, "")),
    /** Episode MP3 directory; defaults to press-pods-audio next to the DB. */
    PRESSPODS_AUDIO_DIR: z.string().optional(),
    PRESSPODS_METADATA_MODEL: z.string().optional(),
    PRESSPODS_CLEANING_MODEL: z.string().optional(),
    /** PressPods TTS backend: self-hosted Higgs (default) or ElevenLabs. */
    PRESSPODS_TTS_PROVIDER: z.enum(["higgs", "elevenlabs"]).default("higgs"),
    /** mlx-audio server base URL (required when the provider is Higgs). */
    PRESSPODS_TTS_URL: z
      .string()
      .optional()
      .transform((s) => s?.replace(/\/+$/, "")),
    /** Optional model-repo override for the Higgs provider. */
    PRESSPODS_TTS_MODEL: z.string().optional(),
    /**
     * OpenAI-compatible STT endpoint used to verify each synthesized chunk is
     * complete (catches Higgs truncation/looping the duration check can't).
     * Defaults to PRESSPODS_TTS_URL — the mlx-audio host already serves an ASR
     * model, so verification is local and $0. Unset (and no TTS URL) disables
     * content verification, falling back to the duration-band check.
     */
    PRESSPODS_STT_URL: z
      .string()
      .optional()
      .transform((s) => s?.replace(/\/+$/, "")),
    /** STT model id (default mlx-community/parakeet-tdt-0.6b-v3). */
    PRESSPODS_STT_MODEL: z.string().optional(),
    /**
     * Reference-voice cloning for Higgs (pins one consistent voice across
     * chunks — without it Higgs picks a random speaker per request). The path
     * must resolve on the mlx-audio host (the M5), not on this box; REF_TEXT is
     * the reference clip's transcript. Both must be set to take effect.
     */
    PRESSPODS_HIGGS_REF_AUDIO: z.string().optional(),
    PRESSPODS_HIGGS_REF_TEXT: z.string().optional(),
    /** ElevenLabs API key — required when the provider is ElevenLabs. */
    ELEVENLABS_API_KEY: z.string().optional(),
    /** Optional voice-id overrides for male / female author narration. */
    ELEVENLABS_VOICE_MALE: z.string().optional(),
    ELEVENLABS_VOICE_FEMALE: z.string().optional(),
    /** Voxtral: retired from PressPods; still used by the tts-bakeoff tool. */
    MISTRAL_API_KEY: z.string().optional(),
    JINA_API_KEY: z.string().optional(),
    PUSHOVER_PRESSPODS_TOKEN: z.string().optional(),
    /** Shared bearer token used only by the private Omni Live app/extension. */
    IOS_CONTROL_AUTH_TOKEN: z.string().min(24).optional(),
    /** Fallback tap target when fewer than four channels are live. */
    IOS_CONTROL_HOME_URL: z
      .string()
      .url()
      .optional()
      .default("http://omni.boris")
      .transform((s) => s.replace(/\/+$/, "")),
    /** APNs token-signing details. All four are required to enable pushes. */
    IOS_CONTROL_APNS_TEAM_ID: z.string().optional(),
    IOS_CONTROL_APNS_KEY_ID: z.string().optional(),
    IOS_CONTROL_APNS_KEY_PATH: z.string().optional(),
    IOS_CONTROL_BUNDLE_ID: z.string().optional().default("com.micthiesen.OmniLive"),
  })
  .transform((c) => ({
    ...c,
    EMAIL_TRANSPORT:
      c.EMAIL_TRANSPORT ??
      (c.FASTMAIL_API_TOKEN
        ? ("fastmail" as const)
        : c.ICLOUD_USERNAME && c.ICLOUD_APP_PASSWORD
          ? ("icloud" as const)
          : undefined),
    EMAIL_SELF_ADDRESS:
      c.EMAIL_SELF_ADDRESS ??
      (c.EMAIL_TRANSPORT === "icloud"
        ? c.ICLOUD_USERNAME
        : c.EMAIL_TRANSPORT === "fastmail"
          ? c.FASTMAIL_USERNAME
          : (c.ICLOUD_USERNAME ?? c.FASTMAIL_USERNAME)),
    PUSHOVER_LIVE_TOKEN: c.PUSHOVER_LIVE_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_BRIEFING_TOKEN: c.PUSHOVER_BRIEFING_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_WORKSPACE_TOKEN: c.PUSHOVER_WORKSPACE_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_CALENDAR_TOKEN: c.PUSHOVER_CALENDAR_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_RECS_TOKEN: c.PUSHOVER_RECS_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_PODCAST_TOKEN: c.PUSHOVER_PODCAST_TOKEN ?? c.PUSHOVER_TOKEN,
    PUSHOVER_PRESSPODS_TOKEN: c.PUSHOVER_PRESSPODS_TOKEN ?? c.PUSHOVER_TOKEN,
  }));

export type Config = z.infer<typeof configSchema>;

const config = configSchema.parse(process.env);
validateMcpTokenConfiguration(config.OMNI_MCP_TOKEN, config.DOCKERIZED);
logConfig(config);

export default config;
