// Generates crates/omni-config/tests/golden/config.json: the decoded TS config
// (src/utils/config.ts loadConfigEffect) or a failure for each environment.
// Run from the repository root with an empty environment so the module's own
// boot decode succeeds:
//   env -i PATH="$PATH" node_modules/.bin/tsx crates/omni-config/scripts/golden-config.mts
import { writeFileSync } from "node:fs";
import { Effect, Exit } from "effect";
import { loadConfigEffect } from "../../../src/utils/config.ts";

const strong = "0123456789abcdefghijklmnopqrstuv";
const strong2 = "zyxwvutsrqponmlkjihgfedcba987654";
const cases: Record<string, Record<string, string>> = {
  defaults: {},
  "spec:coercions": {
    OFFLINE_NOTIFICATIONS: "FALSE", LIVESTREAM_INTELLIGENCE_ENABLED: "true", LIVESTREAM_MONTHLY_BUDGET_USD: "4.5",
    LIVESTREAM_MAX_VOICE_TARGETS: "8", PLEX_ACCOUNT_ID: "", FRONTEND_PORT: "4100",
    WORKSPACES_PUBLIC_URL: "https://omni.example///", IOS_CONTROL_HOME_URL: "https://omni.example///",
    PRINTER_IPP_URL: "ipps://printer.example/ipp/print", HISTER_URL: "http://hister:4433/",
    CASTRO_ACCESS_ID: "550e8400-e29b-41d4-a716-446655440000", WHISKER_CREDENTIALS: "person@example.com:pass:with:colons",
  },
  "spec:legacy-empty": {
    LIVESTREAM_MONTHLY_BUDGET_USD: "", LIVESTREAM_DESTINY_SPEAKER_THRESHOLD: "", LIVESTREAM_MAX_VOICE_TARGETS: "",
    SMTP_PORT: "", FRONTEND_PORT: "",
  },
  "spec:derive": {
    ICLOUD_USERNAME: "icloud@example.com", ICLOUD_APP_PASSWORD: "app-password", PUSHOVER_TOKEN: "shared-pushover-token",
    PUSHOVER_RECS_TOKEN: "recommendations-token",
  },
  "spec:fastmail-ignored": { EMAIL_TRANSPORT: "fastmail", FASTMAIL_API_TOKEN: "obsolete", FASTMAIL_USERNAME: "o@example.com" },
  "email-from:fixed": { EMAIL_FROM: "michael@thiesen.dev" },
  "email-from:empty": { EMAIL_FROM: "" },
  "email-from:other": { EMAIL_FROM: "micthiesen@icloud.com" },
  "invalid:budget": { LIVESTREAM_MONTHLY_BUDGET_USD: "10.01" },
  "invalid:threshold": { LIVESTREAM_DESTINY_SPEAKER_THRESHOLD: "-0.1" },
  "invalid:guest-picks": { PODCAST_MAX_GUEST_PICKS: "0" },
  "invalid:castro": { CASTRO_ACCESS_ID: "not-a-uuid" },
  "invalid:printer-scheme": { PRINTER_IPP_URL: "https://printer.example/ipp/print" },
  "invalid:ios-token": { IOS_CONTROL_AUTH_TOKEN: "too-short" },
  "invalid:whisker": { WHISKER_CREDENTIALS: "missing-password:" },
  "invalid:dockerized": { DOCKERIZED: "prod" },
  "invalid:offline": { OFFLINE_NOTIFICATIONS: "yes" },
  "hister:file": { HISTER_URL: "file:///tmp/index" },
  "hister:credentials": { HISTER_URL: "https://user:password@hister.test" },
  "hister:query": { HISTER_URL: "https://hister.test?token=secret" },
  "hister:fragment": { HISTER_URL: "https://hister.test/#fragment" },
  "hister:empty-query": { HISTER_URL: "https://hister.test/?" },
  "hister:uppercase": { HISTER_URL: "HTTPS://Hister.Test/path//" },
  "hister:username-only": { HISTER_URL: "https://user@hister.test" },
  "hister:not-url": { HISTER_URL: "hister" },
  "mcp:docker-missing": { DOCKERIZED: "true" },
  "mcp:docker-strong": { DOCKERIZED: "true", OMNI_MCP_TOKEN: strong },
  "mcp:docker-weak": { DOCKERIZED: "true", OMNI_MCP_TOKEN: "a".repeat(40) },
  "mcp:dev-empty": { OMNI_MCP_TOKEN: "" },
  "mcp:dev-weak": { OMNI_MCP_TOKEN: "short" },
  "mcp:whitespace": { OMNI_MCP_TOKEN: `${strong} x` },
  "device:equal": { OMNI_MCP_TOKEN: strong, OMNI_DEVICE_LINK_TOKEN: strong },
  "device:weak": { OMNI_MCP_TOKEN: strong, OMNI_DEVICE_LINK_TOKEN: "weak" },
  "device:empty": { OMNI_MCP_TOKEN: strong, OMNI_DEVICE_LINK_TOKEN: "" },
  "device:ok": { OMNI_MCP_TOKEN: strong, OMNI_DEVICE_LINK_TOKEN: strong2 },
  "device:without-mcp": { OMNI_DEVICE_LINK_TOKEN: strong2 },
  "bool:upper": { DOCKERIZED: "TRUE", OMNI_MCP_TOKEN: strong, ARR_RECOVERY_ENABLED: "False" },
  "bool:empty": { ARR_RECOVERY_LOCAL_FILES: "" },
  "log-level:upper": { LOG_LEVEL: "INFO" },
  "log-level:warn": { LOG_LEVEL: "warn" },
  "log-level:empty": { LOG_LEVEL: "" },
  "plex:zero": { PLEX_ACCOUNT_ID: "0" },
  "plex:ok": { PLEX_ACCOUNT_ID: "12" },
  "plex:fraction": { PLEX_ACCOUNT_ID: "1.5" },
  "plex:padded": { PLEX_ACCOUNT_ID: " 7 " },
  "plex:hex": { PLEX_ACCOUNT_ID: "0x10" },
  "plex:blank": { PLEX_ACCOUNT_ID: "  " },
  "quality:ok": { RADARR_QUALITY_PROFILE_ID: "4", SONARR_QUALITY_PROFILE_ID: "1e1" },
  "smtp:text": { SMTP_PORT: "abc" },
  "smtp:465": { SMTP_PORT: "465", SMTP_HOST: "smtp.example", SMTP_USER: "u", SMTP_PASS: "p" },
  "smtp:exp": { SMTP_PORT: "1e3" },
  "smtp:negative": { SMTP_PORT: "-25" },
  "smtp:infinity": { SMTP_PORT: "Infinity" },
  "port:padded": { FRONTEND_PORT: " 4100 " },
  "budget:max": { LIVESTREAM_MONTHLY_BUDGET_USD: "10" },
  "budget:negative": { LIVESTREAM_MONTHLY_BUDGET_USD: "-1" },
  "budget:blank": { LIVESTREAM_MONTHLY_BUDGET_USD: "  " },
  "voice:blank": { LIVESTREAM_MAX_VOICE_TARGETS: "  " },
  "voice:all": {
    LIVESTREAM_VOICE_SAMPLE_SECONDS: "20", LIVESTREAM_VOICE_SAMPLE_INTERVAL_SECONDS: "60",
    LIVESTREAM_SUMMARY_SAMPLE_SECONDS: "90", LIVESTREAM_SUMMARY_INTERVAL_SECONDS: "600",
    PODCAST_VOICE_ROTATION_MAX: "3", PODCAST_MAX_GUEST_PICKS: "2",
  },
  "threshold:one": { LIVESTREAM_DESTINY_SPEAKER_THRESHOLD: "1" },
  "threshold:over": { LIVESTREAM_DESTINY_SPEAKER_THRESHOLD: "1.0001" },
  "origin:empty": { WORKSPACES_PUBLIC_URL: "" },
  "origin:presspods": { PRESSPODS_PUBLIC_URL: "https://x.example//", PRESSPODS_TTS_URL: "http://tts:8000/", PRESSPODS_STT_URL: "x/" },
  "ios-home:not-url": { IOS_CONTROL_HOME_URL: "not a url" },
  "ios-home:empty": { IOS_CONTROL_HOME_URL: "" },
  "ios-token:24": { IOS_CONTROL_AUTH_TOKEN: "x".repeat(24) },
  "ios-token:emoji": { IOS_CONTROL_AUTH_TOKEN: "😀".repeat(12) },
  "printer:ipp": { PRINTER_IPP_URL: "ipp://printer.local/x" },
  "printer:upper": { PRINTER_IPP_URL: "IPP://printer.local" },
  "printer:invalid": { PRINTER_IPP_URL: "ipp//" },
  "tts:elevenlabs": { PRESSPODS_TTS_PROVIDER: "elevenlabs" },
  "tts:mixed-case": { PRESSPODS_TTS_PROVIDER: "ElevenLabs" },
  "model:luna": { LIVESTREAM_INTELLIGENCE_MODEL: "openai:gpt-6-luna" },
  "model:sol": { LIVESTREAM_INTELLIGENCE_MODEL: "openai:gpt-6-sol" },
  "whisker:leading": { WHISKER_CREDENTIALS: ":x" },
  "whisker:ok": { WHISKER_CREDENTIALS: "a:b" },
  "castro:upper": { CASTRO_ACCESS_ID: "550E8400-E29B-41D4-A716-446655440000" },
  "castro:nil": { CASTRO_ACCESS_ID: "00000000-0000-0000-0000-000000000000" },
  "castro:v9": { CASTRO_ACCESS_ID: "550e8400-e29b-91d4-a716-446655440000" },
  "strings:empty": { DB_NAME: "", TZ: "", WORKSPACE_SCHEDULE: "", ICLOUD_USERNAME: "", EMAIL_SELF_ADDRESS: "" },
  "strings:all-optional": {
    PUSHOVER_USER: "u", KICK_CLIENT_ID: "k", KICK_CLIENT_SECRET: "ks", PUSHOVER_LIVE_TOKEN: "pl",
    LIVESTREAM_DESTINY_VOICEPRINT_PATH: "/v", LIVESTREAM_MODEL_DIR: "/m", PUSHOVER_CALENDAR_TOKEN: "pc",
    PUSHOVER_BRIEFING_TOKEN: "pb", PUSHOVER_WORKSPACE_TOKEN: "pw", BRIEFING_MODEL: "openai:x", WORKSPACE_MODEL: "openai:y",
    GOOGLE_GENERATIVE_AI_API_KEY: "g", ANTHROPIC_API_KEY: "a", OPENAI_API_KEY: "o", TAVILY_API_KEY: "t", LOGS_PATH: "/l",
    CHANNELS_CONFIG_PATH: "/c", BRIEFINGS_PATH: "/b", ICLOUD_REMINDERS_ENABLED: "true", ICLOUD_REMINDERS_ACCOUNT: "ra",
    ICLOUD_REMINDERS_PASSWORD: "rp", ICLOUD_REMINDERS_STORAGE_KEY: "rk", ICLOUD_REMINDERS_PUBLIC_ORIGIN: "https://r",
    ICLOUD_CALENDAR_NAME: "cal", ICLOUD_CALENDAR_URL: "https://cal", EMAIL_SELF_ADDRESS: "me@x", PARCEL_API_KEY: "pa",
    KARAKEEP_URL: "https://k", KARAKEEP_API_KEY: "kk", EXTRACTION_MODEL: "e", CALENDAR_EXTRACTION_MODEL: "ce",
    TRIAGE_MODEL: "tr", TMDB_API_KEY: "tm", RECS_SHORTLIST_MODEL: "rs", RECS_SELECTION_MODEL: "rsel",
    TASTE_REFLECTION_MODEL: "trm", TASTE_REFLECTION_SCHEDULE: "0 0 1 * * *", RECS_SCHEDULE: "0 0 2 * * *",
    RECS_PUBLIC_URL: "https://recs/", PUSHOVER_RECS_TOKEN: "pr", PODCAST_RECS_SCHEDULE: "0 0 3 * * *",
    PODCAST_TASTE_PATH: "/pt", PODCAST_TASTE_REFLECTION_MODEL: "ptm", PODCAST_TASTE_REFLECTION_SCHEDULE: "0 0 4 * * *",
    PUSHOVER_PODCAST_TOKEN: "pp", CASTRO_SECRET_KEY: "cs", PODCASTINDEX_KEY: "pk", PODCASTINDEX_SECRET: "ps",
    PLEX_URL: "https://plex", PLEX_TOKEN: "pt", RADARR_URL: "https://radarr", RADARR_API_KEY: "ra",
    RADARR_ROOT_FOLDER_PATH: "/movies", SONARR_URL: "https://sonarr", SONARR_API_KEY: "sa", SONARR_ROOT_FOLDER_PATH: "/tv",
    OBSERVER_URL: "https://obs", OBSERVER_API_KEY: "oa", OBSERVER_REPAIR_ENABLED: "false", NZBGET_URL: "https://nzb",
    TZ: "Europe/Berlin", LOGS_EMAIL_TO: "logs@x", OMNI_EVENTS_EXECUTOR_AUTH_URL: "https://exec",
    HISTER_ACCESS_TOKEN: "ha", PRESSPODS_AUTH_TOKEN: "pat", PRESSPODS_AUDIO_DIR: "/audio", PRESSPODS_METADATA_MODEL: "pm",
    PRESSPODS_CLEANING_MODEL: "pcm", PRESSPODS_TTS_MODEL: "ttsm", PRESSPODS_STT_MODEL: "sttm",
    PRESSPODS_HIGGS_REF_AUDIO: "/ref.wav", PRESSPODS_HIGGS_REF_TEXT: "ref", ELEVENLABS_API_KEY: "el",
    ELEVENLABS_VOICE_MALE: "m", ELEVENLABS_VOICE_FEMALE: "f", MISTRAL_API_KEY: "mi", JINA_API_KEY: "j",
    PUSHOVER_PRESSPODS_TOKEN: "ppt", IOS_CONTROL_APNS_TEAM_ID: "team", IOS_CONTROL_APNS_KEY_ID: "key",
    IOS_CONTROL_APNS_KEY_PATH: "/k.p8", IOS_CONTROL_BUNDLE_ID: "com.x", LIVESTREAM_INTELLIGENCE_ENABLED: "TRUE",
  },
};

const out = Object.entries(cases).map(([name, env]) => {
  const exit = Effect.runSyncExit(loadConfigEffect(env));
  if (Exit.isSuccess(exit)) return { name, env, ok: true, config: JSON.parse(JSON.stringify(exit.value)) };
  return { name, env, ok: false };
});
writeFileSync(new URL("../tests/golden/config.json", import.meta.url), `${JSON.stringify(out, null, 1)}\n`);
console.error(`wrote ${out.length} cases; ${out.filter((c) => c.ok).length} ok`);
